name: Build and Deploy API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore MovieCatalog.Api/MovieCatalog.Api.csproj

    - name: Build
      run: dotnet build MovieCatalog.Api/MovieCatalog.Api.csproj --no-restore --configuration Release

    - name: Run tests (if you add a test project later)
      run: dotnet test --no-build --verbosity normal || echo "No tests found"

    - name: Publish app
      run: dotnet publish MovieCatalog.Api/MovieCatalog.Api.csproj -c Release -o publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: moviecatalogapi${{ github.actor }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
        